# Generated by Django 3.2.9 on 2021-12-10 13:19

import apps.media.models.fields.image
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_file'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=apps.media.models.fields.image.ImageField(blank=True, help_text='HT__AVATAR', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.image', verbose_name='VN__AVATAR'),
        ),
    ]
