# Generated by Django 4.1.3 on 2022-11-26 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_auto_20211124_1552"),
    ]

    operations = [
        migrations.CreateModel(
            name="SwaggerImport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="HT__CREATED_AT",
                        verbose_name="VN__CREATED_AT",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="HT__UPDATED_AT",
                        verbose_name="VN__UPDATED_AT",
                    ),
                ),
                (
                    "status",
                    models.TextField(
                        blank=True,
                        choices=[
                            ("created", "VN__CREATED"),
                            ("started", "VN__STARTED"),
                            ("finished", "VN__FINISHED"),
                        ],
                        default="created",
                        help_text="HT__STATUS",
                        verbose_name="VN__STATUS",
                    ),
                ),
                (
                    "swagger_content",
                    models.TextField(
                        help_text="HT__SWAGGER_CONTENT",
                        verbose_name="VN__SWAGGER_CONTENT",
                    ),
                ),
                (
                    "swagger_url",
                    models.TextField(
                        help_text="HT__SWAGGER_URL",
                        verbose_name="VN__SWAGGER_URL",
                    ),
                ),
                (
                    "log",
                    models.TextField(
                        help_text="HT__LOG", verbose_name="VN__LOG"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="HT__PROJECT",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                        verbose_name="VN__PROJECT",
                    ),
                ),
            ],
            options={
                "verbose_name": "VN__SWAGGER_IMPORT",
                "verbose_name_plural": "VN__SWAGGER_IMPORT",
            },
        ),
    ]
