# Generated by Django 4.1.3 on 2022-11-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_swaggerimport"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="swaggerimport",
            name="status",
        ),
        migrations.AddField(
            model_name="swaggerimport",
            name="state",
            field=models.TextField(
                blank=True,
                choices=[
                    ("created", "VN__CREATED"),
                    ("running", "VN__RINNING"),
                    ("failed", "VN__FAILED"),
                    ("done", "VN__DONE"),
                ],
                default="created",
                help_text="HT__STATE",
                verbose_name="VN__STATE",
            ),
        ),
    ]
