# Generated by Django 4.1.3 on 2022-11-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_alter_projectasset_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="swaggerimport",
            name="log",
            field=models.TextField(
                default="", help_text="HT__LOG", verbose_name="VN__LOG"
            ),
        ),
        migrations.AlterField(
            model_name="swaggerimport",
            name="swagger_content",
            field=models.TextField(
                default="",
                help_text="HT__SWAGGER_CONTENT",
                verbose_name="VN__SWAGGER_CONTENT",
            ),
        ),
        migrations.AlterField(
            model_name="swaggerimport",
            name="swagger_url",
            field=models.TextField(
                default="",
                help_text="HT__SWAGGER_URL",
                verbose_name="VN__SWAGGER_URL",
            ),
        ),
    ]
