# Generated by Django 4.1.3 on 2022-11-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_alter_swaggerimport_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectasset",
            name="source",
            field=models.TextField(
                choices=[("FIGMA", "CH__FIGMA"), ("UPLOAD", "CH__UPLOAD")],
                default="FIGMA",
                help_text="HT__PROJECT_ASSET_SOURCE",
                verbose_name="VN__PROJECT_ASSET_SOURCE",
            ),
        ),
    ]
