from decouple import config

MINIO_STORAGE_ENDPOINT = config("MINIO_ENDPOINT", default=None)
MINIO_STORAGE_ACCESS_KEY = config("MINIO_ACCESS_KEY", default=None)
MINIO_STORAGE_SECRET_KEY = config("MINIO_SECRET_KEY", default=None)
MINIO_STORAGE_USE_HTTPS = False
MINIO_STORAGE_MEDIA_BUCKET_NAME = "media"
MINIO_STORAGE_AUTO_CREATE_MEDIA_BUCKET = True
