# Generated by Django 3.2.9 on 2022-01-14 09:18

import apps.media.models.file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='storage_file',
            field=models.FileField(help_text='HT__STORAGE_FILE', max_length=1000, upload_to=apps.media.models.file.get_upload_path, verbose_name='VN__STORAGE_FILE'),
        ),
    ]
