# Generated by Django 3.2.9 on 2021-11-06 14:02

import apps.media.models.image
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='HT__CREATED_AT', verbose_name='VN__CREATED_AT')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='HT__UPDATED_AT', verbose_name='VN__UPDATED_AT')),
                ('storage_image', models.ImageField(help_text='HT__STORAGE_IMAGE', max_length=1000, upload_to=apps.media.models.image.get_upload_path, verbose_name='VN__STORAGE_IMAGE')),
                ('original_filename', models.CharField(blank=True, help_text='HT__ORIGINAL_FILENAME', max_length=512, verbose_name='VN__ORIGINAL_FILENAME')),
            ],
            options={
                'verbose_name': 'VN__IMAGE',
                'verbose_name_plural': 'VN__IMAGES',
            },
        ),
    ]
