version: '3.7'

x-base-app: &base-app
  build:
    context: ../
    dockerfile: docker/Dockerfile
    target: test
  volumes:
    - ../server:/app/server
  environment:
    DJANGO_ENV: development

services:
  server:
    <<: *base-app
    command: [ "python", "server/manage.py", "runserver", "0.0.0.0:8000" ]
    ports:
      - "127.0.0.1:8000:8000"

  celery-worker:
    <<: *base-app
    command: [ "make", "-f", "docker/server/Makefile", "celery-worker" ]

  celery-beat:
    <<: *base-app
    command: [ "make", "-f", "docker/server/Makefile", "celery-beat" ]

  flower:
    <<: *base-app
    command: [ "make", "-f", "docker/server/Makefile", "flower" ]
    ports:
      - "127.0.0.1:5555:5555"
