version: '3.7'

x-healthcheck: &healthcheck
  interval: 10s
  timeout: 5s
  retries: 5

services:
  postgres:
    image: postgres:15.1
    shm_size: 2gb
    ports:
      - "127.0.0.1:5432:5432"
    env_file:
      - config.env
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      <<: *healthcheck
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]

  couchdb:
    image: couchdb:3.0.1
    ports:
      - "127.0.0.1:5984:5984"
    env_file:
      - config.env
    volumes:
      - ./couchdb/data:/opt/couchdb/data
      - ./couchdb/config:/opt/couchdb/etc/local.d

  redis:
    image: redis:6.2.6
    ports:
      - "6379:6379"
    healthcheck:
      <<: *healthcheck
      test: [ "CMD-SHELL", "redis-cli", "--raw", "incr", "ping" ]

volumes:
  pg-data:
