# Generated by Django 3.2.9 on 2022-02-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='HT__CREATED_AT', null=True, verbose_name='VN__CREATED_AT'),
        ),
    ]
