name: CI/CD

on: [ pull_request, push ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/${{ github.repository }}
  DOCKER_IMAGE_TEST: app_test:${{ github.sha }}
  DOCKER_IMAGE_TEST_ARTIFACT: test_image_${{ github.sha }}
  DOCKER_IMAGE_TEST_PATH: /tmp/test_image.tar

jobs:
  preflight:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Running hadolint
        uses: hadolint/hadolint-action@v1.6.0
        with:
          dockerfile: devops/docker/Dockerfile

      - name: Running yaml lint
        uses: "docker://pipelinecomponents/yamllint:0.21.1"
        with:
          args: yamllint .

      - name: Running shellcheck
        uses: "docker://pipelinecomponents/shellcheck:0.11.4"
        with:
          args: bash -c "find . -name \*.sh -type f -print0 | xargs -0 -P $(nproc) -r -n1 shellcheck"

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk.sarif


  build-test-image:
    runs-on: ubuntu-20.04
    needs: preflight
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build test Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: devops/docker/Dockerfile
          push: false
          tags: ${{ env.DOCKER_IMAGE_TEST }}
          target: test
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:_buildcache
          cache-to: type=registry,ref=${{ env.IMAGE_NAME }}:_buildcache,mode=max
          outputs: type=docker,dest=${{ env.DOCKER_IMAGE_TEST_PATH }}

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.DOCKER_IMAGE_TEST_ARTIFACT }}
          path: ${{ env.DOCKER_IMAGE_TEST_PATH }}
          retention-days: 1

  lint:
    runs-on: ubuntu-20.04
    needs: build-test-image
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.DOCKER_IMAGE_TEST_ARTIFACT }}
          path: /tmp

      - name: Load Docker image
        run: |
          docker load --input ${{ env.DOCKER_IMAGE_TEST_PATH }}
      - name: Lint
        run: |
          docker run ${{ env.DOCKER_IMAGE_TEST }} make lint

  test:
    runs-on: ubuntu-20.04
    needs: build-test-image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.DOCKER_IMAGE_TEST_ARTIFACT }}
          path: /tmp

      - name: Load Docker image
        run: |
          docker load --input ${{ env.DOCKER_IMAGE_TEST_PATH }}

      - name: Test
        env:
          APP_TEST_IMAGE: ${{ env.DOCKER_IMAGE_TEST }}
        run: |
          docker-compose -f devops/ci/docker-compose.yml up --exit-code-from app

  build:
    runs-on: ubuntu-20.04
    needs: [ lint, test ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=sha,priority=300
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}

      - name: Build production and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: devops/docker/Dockerfile
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          target: production
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:_buildcache
          cache-to: type=registry,ref=${{ env.IMAGE_NAME }}:_buildcache,mode=max

    outputs:
      tag: ${{ steps.meta.outputs.version  }}

  deploy:
    runs-on: ubuntu-20.04
    needs: build
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Deploy
        run: curl -k -X POST -d "component=${{ secrets.DEPLOYER_COMPONENT }}&key=${{ secrets.DEPLOYER_KEY }}&tag=${{ needs.build.outputs.tag }}" ${{ secrets.DEPLOYER_HOST }}
